service:
  name: prototypes-quiz

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  deploymentBucket:
    name: sls-deploys-${self:service}-${self:provider.stage}-${self:provider.region}
    serverSideEncryption: AES256
  runtime: nodejs6.10

plugins:
#  - serverless-webpack
  - serverless-finch

custom:
  client:
    bucketName: ${self:service}
    distributionFolder: website
